FROM msyksphinz/msrh:run_env

WORKDIR /work
COPY . /work/

WORKDIR /work/tests/riscv-tests
RUN ["./configure"]
RUN ["make", "-j20"]

WORKDIR /work/spike_dpi
RUN ["make", "all"]

WORKDIR /work/verilator_sim
RUN ["/work/scripts/runtest.py", "--isa", "rv64imac", "-c", "tiny", "-t", "sanity", "-j20"]
