FROM msyksphinz/msrh:run_env

WORKDIR /work
COPY . /work/

WORKDIR /work/tests/riscv-tests
RUN ["make", "-j$(nproc)"]

WORKDIR /work/verilator_sim
RUN ["/work/scripts/runtest.py", "--isa", "rv64imac", "-c", "tiny", "-t", "sanity", "-j$(nproc)"]
