add_files -norecurse ../src/decoder_inst_cat.sv
add_files -norecurse ../src/decoder_reg.sv
add_files -norecurse ../src/decoder_alu_ctrl.sv
add_files -norecurse ../src/decoder_lsu_ctrl.sv
add_files -norecurse ../src/msrh_pkg.sv
add_files -norecurse ../src/msrh_lsu_pkg.sv
add_files -norecurse ../src/l2_if.sv
add_files -norecurse ../src/l1d_if.sv
add_files -norecurse ../src/disp_if.sv
add_files -norecurse ../src/regread_if.sv
add_files -norecurse ../src/l1d_lrq_if.sv
add_files -norecurse ../src/lsu_if.sv
add_files -norecurse ../src/bit_cnt.sv
add_files -norecurse ../src/bit_or.sv
add_files -norecurse ../src/bit_oh_or.sv
add_files -norecurse ../src/bit_ff_lsb.sv
add_files -norecurse ../src/bit_extract_msb.sv
add_files -norecurse ../src/bit_tree_msb.sv
add_files -norecurse ../src/bit_extract_lsb.sv
add_files -norecurse ../src/bit_tree_lsb.sv
add_files -norecurse ../src/bit_pick_up.sv
add_files -norecurse ../src/bit_pick_1_index.sv
add_files -norecurse ../src/encoder.sv
add_files -norecurse ../src/inoutptr.sv
add_files -norecurse ../src/inoutptr_var.sv
add_files -norecurse ../src/inoutptr_oh.sv
add_files -norecurse ../src/select_latest.sv
add_files -norecurse ../src/select_latest_1bit.sv
add_files -norecurse ../src/select_oh.sv
add_files -norecurse ../src/select_release_bus.sv
add_files -norecurse ../src/data_array.sv
add_files -norecurse ../src/msrh_icache.sv
add_files -norecurse ../src/tag_array.sv
add_files -norecurse ../src/msrh_frontend.sv
add_files -norecurse ../src/tlb.sv
add_files -norecurse ../src/msrh_tile.sv
add_files -norecurse ../src/msrh_tile_wrapper.sv
add_files -norecurse ../src/msrh_inst_buffer.sv
add_files -norecurse ../src/msrh_disp_pickup.sv
add_files -norecurse ../src/msrh_rename.sv
add_files -norecurse ../src/msrh_freelist.sv
add_files -norecurse ../src/msrh_rename_map.sv
add_files -norecurse ../src/msrh_inflight_list.sv
add_files -norecurse ../src/msrh_scheduler.sv
add_files -norecurse ../src/msrh_sched_entry.sv
add_files -norecurse ../src/msrh_phy_registers.sv
add_files -norecurse ../src/msrh_rob.sv
add_files -norecurse ../src/msrh_rob_entry.sv
add_files -norecurse ../src/msrh_alu.sv
add_files -norecurse ../src/msrh_alu_pipe.sv
add_files -norecurse ../src/msrh_lsu_top.sv
add_files -norecurse ../src/msrh_lsu.sv
add_files -norecurse ../src/msrh_lsu_pipe.sv
add_files -norecurse ../src/msrh_l1d_load_requester.sv
add_files -norecurse ../src/msrh_lrq_entry.sv
add_files -norecurse ../src/msrh_ldq.sv
add_files -norecurse ../src/msrh_ldq_entry.sv
add_files -norecurse ../src/msrh_stq.sv
add_files -norecurse ../src/msrh_stq_entry.sv
add_files -norecurse ../src/msrh_dcache.sv
add_files -norecurse ../src/msrh_dcache_array.sv
