.PHONY: riscv32_big_imac
.PHONY: riscv32_big_imafdc
.PHONY: riscv32_big_imc
.PHONY: riscv32_big_imfc
.PHONY: riscv32_big_imfdc
.PHONY: riscv32_giant_imac
.PHONY: riscv32_giant_imafdc
.PHONY: riscv32_giant_imc
.PHONY: riscv32_giant_imfc
.PHONY: riscv32_giant_imfdc
.PHONY: riscv32_small_imac
.PHONY: riscv32_small_imafdc
.PHONY: riscv32_small_imc
.PHONY: riscv32_small_imfc
.PHONY: riscv32_small_imfdc
.PHONY: riscv32_standard_imac
.PHONY: riscv32_standard_imafdc
.PHONY: riscv32_standard_imc
.PHONY: riscv32_standard_imfc
.PHONY: riscv32_standard_imfdc
.PHONY: riscv32_tiny_imac
.PHONY: riscv32_tiny_imafdc
.PHONY: riscv32_tiny_imc
.PHONY: riscv32_tiny_imfc
.PHONY: riscv32_tiny_imfdc
.PHONY: riscv64_big_imac
.PHONY: riscv64_big_imafdc
.PHONY: riscv64_big_imc
.PHONY: riscv64_big_imfc
.PHONY: riscv64_big_imfdc
.PHONY: riscv64_giant_imac
.PHONY: riscv64_giant_imafdc
.PHONY: riscv64_giant_imc
.PHONY: riscv64_giant_imfc
.PHONY: riscv64_giant_imfdc
.PHONY: riscv64_small_imac
.PHONY: riscv64_small_imafdc
.PHONY: riscv64_small_imc
.PHONY: riscv64_small_imfc
.PHONY: riscv64_small_imfdc
.PHONY: riscv64_standard_imac
.PHONY: riscv64_standard_imafdc
.PHONY: riscv64_standard_imc
.PHONY: riscv64_standard_imfc
.PHONY: riscv64_standard_imfdc
.PHONY: riscv64_tiny_imac
.PHONY: riscv64_tiny_imafdc
.PHONY: riscv64_tiny_imc
.PHONY: riscv64_tiny_imfc
.PHONY: riscv64_tiny_imfdc


TARGET_DIR += riscv32_big_imac
TARGET_DIR += riscv32_big_imafdc
TARGET_DIR += riscv32_big_imc
TARGET_DIR += riscv32_big_imfc
TARGET_DIR += riscv32_big_imfdc
TARGET_DIR += riscv32_giant_imac
TARGET_DIR += riscv32_giant_imafdc
TARGET_DIR += riscv32_giant_imc
TARGET_DIR += riscv32_giant_imfc
TARGET_DIR += riscv32_giant_imfdc
TARGET_DIR += riscv32_small_imac
TARGET_DIR += riscv32_small_imafdc
TARGET_DIR += riscv32_small_imc
TARGET_DIR += riscv32_small_imfc
TARGET_DIR += riscv32_small_imfdc
TARGET_DIR += riscv32_standard_imac
TARGET_DIR += riscv32_standard_imafdc
TARGET_DIR += riscv32_standard_imc
TARGET_DIR += riscv32_standard_imfc
TARGET_DIR += riscv32_standard_imfdc
TARGET_DIR += riscv32_tiny_imac
TARGET_DIR += riscv32_tiny_imafdc
TARGET_DIR += riscv32_tiny_imc
TARGET_DIR += riscv32_tiny_imfc
TARGET_DIR += riscv32_tiny_imfdc
TARGET_DIR += riscv64_big_imac
TARGET_DIR += riscv64_big_imafdc
TARGET_DIR += riscv64_big_imc
TARGET_DIR += riscv64_big_imfc
TARGET_DIR += riscv64_big_imfdc
TARGET_DIR += riscv64_giant_imac
TARGET_DIR += riscv64_giant_imafdc
TARGET_DIR += riscv64_giant_imc
TARGET_DIR += riscv64_giant_imfc
TARGET_DIR += riscv64_giant_imfdc
TARGET_DIR += riscv64_small_imac
TARGET_DIR += riscv64_small_imafdc
TARGET_DIR += riscv64_small_imc
TARGET_DIR += riscv64_small_imfc
TARGET_DIR += riscv64_small_imfdc
TARGET_DIR += riscv64_standard_imac
TARGET_DIR += riscv64_standard_imafdc
TARGET_DIR += riscv64_standard_imc
TARGET_DIR += riscv64_standard_imfc
TARGET_DIR += riscv64_standard_imfdc
TARGET_DIR += riscv64_tiny_imac
TARGET_DIR += riscv64_tiny_imafdc
TARGET_DIR += riscv64_tiny_imc
TARGET_DIR += riscv64_tiny_imfc
TARGET_DIR += riscv64_tiny_imfdc

all_build: $(TARGET_DIR)

$(TARGET_DIR):
	make -C $@
