add_test (name="rv32ui-p-add",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-add"        )
add_test (name="rv32ui-p-addi",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-addi"       )
add_test (name="rv32ui-p-and",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-and"        )
add_test (name="rv32ui-p-andi",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-andi"       )
add_test (name="rv32ui-p-auipc",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-auipc"      )
add_test (name="rv32ui-p-beq",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-beq"        )
add_test (name="rv32ui-p-bge",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-bge"        )
add_test (name="rv32ui-p-bgeu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-bgeu"       )
add_test (name="rv32ui-p-blt",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-blt"        )
add_test (name="rv32ui-p-bltu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-bltu"       )
add_test (name="rv32ui-p-bne",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-bne"        )
add_test (name="rv32ui-p-fence_i",    group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-fence_i"    )
add_test (name="rv32ui-p-jal",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-jal"        )
add_test (name="rv32ui-p-jalr",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-jalr"       )
add_test (name="rv32ui-p-lb",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-lb"         )
add_test (name="rv32ui-p-lbu",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-lbu"        )
add_test (name="rv32ui-p-lh",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-lh"         )
add_test (name="rv32ui-p-lhu",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-lhu"        )
add_test (name="rv32ui-p-lui",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-lui"        )
add_test (name="rv32ui-p-lw",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-lw"         )
add_test (name="rv32ui-p-or",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-or"         )
add_test (name="rv32ui-p-ori",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-ori"        )
add_test (name="rv32ui-p-sb",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-sb"         )
add_test (name="rv32ui-p-sh",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-sh"         )
add_test (name="rv32ui-p-simple",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-simple"     )
add_test (name="rv32ui-p-sll",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-sll"        )
add_test (name="rv32ui-p-slli",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-slli"       )
add_test (name="rv32ui-p-slt",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-slt"        )
add_test (name="rv32ui-p-slti",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-slti"       )
add_test (name="rv32ui-p-sltiu",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-sltiu"      )
add_test (name="rv32ui-p-sltu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-sltu"       )
add_test (name="rv32ui-p-sra",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-sra"        )
add_test (name="rv32ui-p-srai",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-srai"       )
add_test (name="rv32ui-p-srl",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-srl"        )
add_test (name="rv32ui-p-srli",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-srli"       )
add_test (name="rv32ui-p-sub",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-sub"        )
add_test (name="rv32ui-p-sw",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-sw"         )
add_test (name="rv32ui-p-xor",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-xor"        )
add_test (name="rv32ui-p-xori",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-p-xori"       )
                                                              '
add_test (name="rv32mi-p-breakpoint", group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32mi-p-breakpoint" )
add_test (name="rv32mi-p-csr",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32mi-p-csr"        )
add_test (name="rv32mi-p-illegal",    group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32mi-p-illegal"    )
add_test (name="rv32mi-p-ma_addr",    group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32mi-p-ma_addr"    )
add_test (name="rv32mi-p-ma_fetch",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32mi-p-ma_fetch"   )
add_test (name="rv32mi-p-mcsr",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32mi-p-mcsr"       )
# add_test (name="rv32mi-p-sbreak",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'],   elf="riscv-tests/isa/rv32mi-p-sbreak"     )
add_test (name="rv32mi-p-scall",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32mi-p-scall"      )
add_test (name="rv32mi-p-shamt",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32mi-p-shamt"      )
add_test (name="rv32si-p-csr",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32si-p-csr"        )
add_test (name="rv32si-p-dirty",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32si-p-dirty"      )
add_test (name="rv32si-p-ma_fetch",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32si-p-ma_fetch"   )
# add_test (name="rv32si-p-sbreak",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'],   elf="riscv-tests/isa/rv32si-p-sbreak"     )
add_test (name="rv32si-p-scall",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32si-p-scall"      )
add_test (name="rv32si-p-wfi",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32si-p-wfi"        )
                                                              '
add_test (name="rv32ua-p-amoadd_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-amoadd_w"   , skip=True)
add_test (name="rv32ua-p-amoand_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-amoand_w"   , skip=True)
add_test (name="rv32ua-p-amomax_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-amomax_w"   , skip=True)
add_test (name="rv32ua-p-amomaxu_w",  group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-amomaxu_w"  , skip=True)
add_test (name="rv32ua-p-amomin_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-amomin_w"   , skip=True)
add_test (name="rv32ua-p-amominu_w",  group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-amominu_w"  , skip=True)
add_test (name="rv32ua-p-amoor_w",    group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-amoor_w"    , skip=True)
add_test (name="rv32ua-p-amoswap_w",  group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-amoswap_w"  , skip=True)
add_test (name="rv32ua-p-amoxor_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-amoxor_w"   , skip=True)
add_test (name="rv32ua-p-lrsc",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-p-lrsc"       , skip=True)
add_test (name="rv32ua-v-amoadd_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-amoadd_w"   , skip=True)
add_test (name="rv32ua-v-amoand_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-amoand_w"   , skip=True)
add_test (name="rv32ua-v-amomax_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-amomax_w"   , skip=True)
add_test (name="rv32ua-v-amomaxu_w",  group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-amomaxu_w"  , skip=True)
add_test (name="rv32ua-v-amomin_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-amomin_w"   , skip=True)
add_test (name="rv32ua-v-amominu_w",  group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-amominu_w"  , skip=True)
add_test (name="rv32ua-v-amoor_w",    group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-amoor_w"    , skip=True)
add_test (name="rv32ua-v-amoswap_w",  group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-amoswap_w"  , skip=True)
add_test (name="rv32ua-v-amoxor_w",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-amoxor_w"   , skip=True)
add_test (name="rv32ua-v-lrsc",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ua-v-lrsc"       , skip=True)
add_test (name="rv32uc-p-rvc",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uc-p-rvc"        )
add_test (name="rv32uc-v-rvc",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uc-v-rvc"        )
add_test (name="rv32ud-p-fadd",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-fadd"       )
add_test (name="rv32ud-p-fclass",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-fclass"     )
add_test (name="rv32ud-p-fcmp",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-fcmp"       )
add_test (name="rv32ud-p-fcvt",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-fcvt"       )
add_test (name="rv32ud-p-fcvt_w",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-fcvt_w"     )
add_test (name="rv32ud-p-fdiv",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-fdiv"       )
add_test (name="rv32ud-p-fmadd",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-fmadd"      )
add_test (name="rv32ud-p-fmin",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-fmin"       )
add_test (name="rv32ud-p-ldst",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-ldst"       )
add_test (name="rv32ud-p-recoding",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-p-recoding"   )
add_test (name="rv32ud-v-fadd",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-fadd"       )
add_test (name="rv32ud-v-fclass",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-fclass"     )
add_test (name="rv32ud-v-fcmp",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-fcmp"       )
add_test (name="rv32ud-v-fcvt",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-fcvt"       )
add_test (name="rv32ud-v-fcvt_w",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-fcvt_w"     )
add_test (name="rv32ud-v-fdiv",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-fdiv"       )
add_test (name="rv32ud-v-fmadd",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-fmadd"      )
add_test (name="rv32ud-v-fmin",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-fmin"       )
add_test (name="rv32ud-v-ldst",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-ldst"       )
add_test (name="rv32ud-v-recoding",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ud-v-recoding"   )
add_test (name="rv32uf-p-fadd",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-fadd"       )
add_test (name="rv32uf-p-fclass",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-fclass"     )
add_test (name="rv32uf-p-fcmp",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-fcmp"       )
add_test (name="rv32uf-p-fcvt",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-fcvt"       )
add_test (name="rv32uf-p-fcvt_w",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-fcvt_w"     )
add_test (name="rv32uf-p-fdiv",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-fdiv"       )
add_test (name="rv32uf-p-fmadd",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-fmadd"      )
add_test (name="rv32uf-p-fmin",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-fmin"       )
add_test (name="rv32uf-p-ldst",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-ldst"       )
add_test (name="rv32uf-p-move",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-move"       )
add_test (name="rv32uf-p-recoding",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-p-recoding"   )
add_test (name="rv32uf-v-fadd",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-fadd"       )
add_test (name="rv32uf-v-fclass",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-fclass"     )
add_test (name="rv32uf-v-fcmp",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-fcmp"       )
add_test (name="rv32uf-v-fcvt",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-fcvt"       )
add_test (name="rv32uf-v-fcvt_w",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-fcvt_w"     )
add_test (name="rv32uf-v-fdiv",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-fdiv"       )
add_test (name="rv32uf-v-fmadd",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-fmadd"      )
add_test (name="rv32uf-v-fmin",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-fmin"       )
add_test (name="rv32uf-v-ldst",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-ldst"       )
add_test (name="rv32uf-v-move",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-move"       )
add_test (name="rv32uf-v-recoding",   group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32uf-v-recoding"   )
add_test (name="rv32ui-v-add",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-add"        )
add_test (name="rv32ui-v-addi",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-addi"       )
add_test (name="rv32ui-v-and",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-and"        )
add_test (name="rv32ui-v-andi",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-andi"       )
add_test (name="rv32ui-v-auipc",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-auipc"      )
add_test (name="rv32ui-v-beq",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-beq"        )
add_test (name="rv32ui-v-bge",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-bge"        )
add_test (name="rv32ui-v-bgeu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-bgeu"       )
add_test (name="rv32ui-v-blt",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-blt"        )
add_test (name="rv32ui-v-bltu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-bltu"       )
add_test (name="rv32ui-v-bne",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-bne"        )
add_test (name="rv32ui-v-fence_i",    group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-fence_i"    )
add_test (name="rv32ui-v-jal",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-jal"        )
add_test (name="rv32ui-v-jalr",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-jalr"       )
add_test (name="rv32ui-v-lb",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-lb"         )
add_test (name="rv32ui-v-lbu",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-lbu"        )
add_test (name="rv32ui-v-lh",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-lh"         )
add_test (name="rv32ui-v-lhu",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-lhu"        )
add_test (name="rv32ui-v-lui",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-lui"        )
add_test (name="rv32ui-v-lw",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-lw"         )
add_test (name="rv32ui-v-or",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-or"         )
add_test (name="rv32ui-v-ori",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-ori"        )
add_test (name="rv32ui-v-sb",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-sb"         )
add_test (name="rv32ui-v-sh",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-sh"         )
add_test (name="rv32ui-v-simple",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-simple"     )
add_test (name="rv32ui-v-sll",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-sll"        )
add_test (name="rv32ui-v-slli",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-slli"       )
add_test (name="rv32ui-v-slt",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-slt"        )
add_test (name="rv32ui-v-slti",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-slti"       )
add_test (name="rv32ui-v-sltiu",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-sltiu"      )
add_test (name="rv32ui-v-sltu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-sltu"       )
add_test (name="rv32ui-v-sra",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-sra"        )
add_test (name="rv32ui-v-srai",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-srai"       )
add_test (name="rv32ui-v-srl",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-srl"        )
add_test (name="rv32ui-v-srli",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-srli"       )
add_test (name="rv32ui-v-sub",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-sub"        )
add_test (name="rv32ui-v-sw",         group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-sw"         )
add_test (name="rv32ui-v-xor",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-xor"        )
add_test (name="rv32ui-v-xori",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32ui-v-xori"       )
add_test (name="rv32um-p-div",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-p-div"        )
add_test (name="rv32um-p-divu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-p-divu"       )
add_test (name="rv32um-p-mul",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-p-mul"        )
add_test (name="rv32um-p-mulh",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-p-mulh"       )
add_test (name="rv32um-p-mulhsu",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-p-mulhsu"     )
add_test (name="rv32um-p-mulhu",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-p-mulhu"      )
add_test (name="rv32um-p-rem",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-p-rem"        )
add_test (name="rv32um-p-remu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-p-remu"       )
add_test (name="rv32um-v-div",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-v-div"        )
add_test (name="rv32um-v-divu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-v-divu"       )
add_test (name="rv32um-v-mul",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-v-mul"        )
add_test (name="rv32um-v-mulh",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-v-mulh"       )
add_test (name="rv32um-v-mulhsu",     group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-v-mulhsu"     )
add_test (name="rv32um-v-mulhu",      group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-v-mulhu"      )
add_test (name="rv32um-v-rem",        group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-v-rem"        )
add_test (name="rv32um-v-remu",       group=['rv32i', 'rv32imc', 'rv32imfc', 'rv32imfdc'], elf="riscv-tests/isa/rv32um-v-remu"       }

add_test (name="simple_add"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_add/test.elf"        )
add_test (name="long_chain_addi"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="long_chain_addi/test.elf"   )
add_test (name="long_ld_sequence"  , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="long_ld_sequence/test.elf"  )
add_test (name="simple_addi"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_addi/test.elf"       )
add_test (name="simple_addiw"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_addiw/test.elf"      )
add_test (name="simple_auipc"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_auipc/test.elf"      )
add_test (name="simple_branch"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_branch/test.elf"     )
add_test (name="simple_branch2"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_branch2/test.elf"    )
add_test (name="simple_chain_addi" , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_chain_addi/test.elf" )
add_test (name="simple_ld"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_ld/test.elf"         )
add_test (name="simple_lw"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_lw/test.elf"         )
add_test (name="simple_lwu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_lwu/test.elf"        )
add_test (name="simple_lh"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_lh/test.elf"         )
add_test (name="simple_lhu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_lhu/test.elf"        )
add_test (name="simple_lb"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_lb/test.elf"         )
add_test (name="simple_lbu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_lbu/test.elf"        )
add_test (name="simple_lui"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_lui/test.elf"        )
add_test (name="simple_sd"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_sd/test.elf"         )
add_test (name="simple_sw"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_sw/test.elf"         )
add_test (name="simple_sh"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_sh/test.elf"         )
add_test (name="simple_sb"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_sb/test.elf"         )
add_test (name="simple_sub"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="simple_sub/test.elf"        )
add_test (name="x0_rename"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="x0_rename/test.elf"         )
add_test (name="cl_conflict_test"  , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="cl_conflict_test/test.elf"  )
add_test (name="dcache_conflict"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="dcache_conflict/test.elf"   )
add_test (name="ldq_stq_flush"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="ldq_stq_flush/test.elf"     )
add_test (name="ras_check"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="ras_check/test.elf"         )
add_test (name="ras_check2"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="ras_check2/test.elf"        )
add_test (name="memcpy_test"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], elf="memcpy_test/test.elf"       )

add_test (name="rv64ui-p-add"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-add"          )
add_test (name="rv64ui-p-addi"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-addi"         )
add_test (name="rv64ui-p-addiw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-addiw"        )
add_test (name="rv64ui-p-addw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-addw"         )
add_test (name="rv64ui-p-and"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-and"          )
add_test (name="rv64ui-p-andi"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-andi"         )
add_test (name="rv64ui-p-auipc"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-auipc"        )
add_test (name="rv64ui-p-beq"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-beq"          )
add_test (name="rv64ui-p-bge"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-bge"          )
add_test (name="rv64ui-p-bgeu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-bgeu"         )
add_test (name="rv64ui-p-blt"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-blt"          )
add_test (name="rv64ui-p-bltu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-bltu"         )
add_test (name="rv64ui-p-bne"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-bne"          )
add_test (name="rv64ui-p-fence_i"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-fence_i"      )
add_test (name="rv64ui-p-jal"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-jal"          )
add_test (name="rv64ui-p-jalr"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-jalr"         )
add_test (name="rv64ui-p-lb"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-lb"           )
add_test (name="rv64ui-p-lbu"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-lbu"          )
add_test (name="rv64ui-p-ld"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-ld"           )
add_test (name="rv64ui-p-lh"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-lh"           )
add_test (name="rv64ui-p-lhu"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-lhu"          )
add_test (name="rv64ui-p-lui"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-lui"          )
add_test (name="rv64ui-p-lw"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-lw"           )
add_test (name="rv64ui-p-lwu"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-lwu"          )
add_test (name="rv64ui-p-or"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-or"           )
add_test (name="rv64ui-p-ori"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-ori"          )
add_test (name="rv64ui-p-sb"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sb"           )
add_test (name="rv64ui-p-sd"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sd"           )
add_test (name="rv64ui-p-sh"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sh"           )
add_test (name="rv64ui-p-simple"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-simple"       )
add_test (name="rv64ui-p-sll"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sll"          )
add_test (name="rv64ui-p-slli"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-slli"         )
add_test (name="rv64ui-p-slliw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-slliw"        )
add_test (name="rv64ui-p-sllw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sllw"         )
add_test (name="rv64ui-p-slt"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-slt"          )
add_test (name="rv64ui-p-slti"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-slti"         )
add_test (name="rv64ui-p-sltiu"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sltiu"        )
add_test (name="rv64ui-p-sltu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sltu"         )
add_test (name="rv64ui-p-sra"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sra"          )
add_test (name="rv64ui-p-srai"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-srai"         )
add_test (name="rv64ui-p-sraiw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sraiw"        )
add_test (name="rv64ui-p-sraw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sraw"         )
add_test (name="rv64ui-p-srl"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-srl"          )
add_test (name="rv64ui-p-srli"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-srli"         )
add_test (name="rv64ui-p-srliw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-srliw"        )
add_test (name="rv64ui-p-srlw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-srlw"         )
add_test (name="rv64ui-p-sub"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sub"          )
add_test (name="rv64ui-p-subw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-subw"         )
add_test (name="rv64ui-p-sw"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-sw"           )
add_test (name="rv64ui-p-xor"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-xor"          )
add_test (name="rv64ui-p-xori"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-p-xori"         )
                                        group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],
add_test (name="rv64ui-v-add"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-add"          )
add_test (name="rv64ui-v-addi"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-addi"         )
add_test (name="rv64ui-v-addiw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-addiw"        )
add_test (name="rv64ui-v-addw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-addw"         )
add_test (name="rv64ui-v-and"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-and"          )
add_test (name="rv64ui-v-andi"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-andi"         )
add_test (name="rv64ui-v-auipc"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-auipc"        )
add_test (name="rv64ui-v-beq"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-beq"          )
add_test (name="rv64ui-v-bge"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-bge"          )
add_test (name="rv64ui-v-bgeu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-bgeu"         )
add_test (name="rv64ui-v-blt"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-blt"          )
add_test (name="rv64ui-v-bltu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-bltu"         )
add_test (name="rv64ui-v-bne"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-bne"          )
add_test (name="rv64ui-v-fence_i"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-fence_i"      )
add_test (name="rv64ui-v-jal"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-jal"          )
add_test (name="rv64ui-v-jalr"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-jalr"         )
add_test (name="rv64ui-v-lb"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-lb"           )
add_test (name="rv64ui-v-lbu"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-lbu"          )
add_test (name="rv64ui-v-ld"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-ld"           )
add_test (name="rv64ui-v-lh"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-lh"           )
add_test (name="rv64ui-v-lhu"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-lhu"          )
add_test (name="rv64ui-v-lui"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-lui"          )
add_test (name="rv64ui-v-lw"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-lw"           )
add_test (name="rv64ui-v-lwu"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-lwu"          )
add_test (name="rv64ui-v-or"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-or"           )
add_test (name="rv64ui-v-ori"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-ori"          )
add_test (name="rv64ui-v-sb"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sb"           )
add_test (name="rv64ui-v-sd"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sd"           )
add_test (name="rv64ui-v-sh"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sh"           )
add_test (name="rv64ui-v-simple"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-simple"       )
add_test (name="rv64ui-v-sll"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sll"          )
add_test (name="rv64ui-v-slli"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-slli"         )
add_test (name="rv64ui-v-slliw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-slliw"        )
add_test (name="rv64ui-v-sllw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sllw"         )
add_test (name="rv64ui-v-slt"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-slt"          )
add_test (name="rv64ui-v-slti"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-slti"         )
add_test (name="rv64ui-v-sltiu"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sltiu"        )
add_test (name="rv64ui-v-sltu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sltu"         )
add_test (name="rv64ui-v-sra"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sra"          )
add_test (name="rv64ui-v-srai"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-srai"         )
add_test (name="rv64ui-v-sraiw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sraiw"        )
add_test (name="rv64ui-v-sraw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sraw"         )
add_test (name="rv64ui-v-srl"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-srl"          )
add_test (name="rv64ui-v-srli"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-srli"         )
add_test (name="rv64ui-v-srliw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-srliw"        )
add_test (name="rv64ui-v-srlw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-srlw"         )
add_test (name="rv64ui-v-sub"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sub"          )
add_test (name="rv64ui-v-subw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-subw"         )
add_test (name="rv64ui-v-sw"          , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-sw"           )
add_test (name="rv64ui-v-xor"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-xor"          )
add_test (name="rv64ui-v-xori"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ui-v-xori"         )
add_test (name="rv64mi-p-access"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64mi-p-access"       )
#  add_test (name="rv64mi-p-breakpoint" group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], ,         elf="riscv-tests/isa/rv64mi-p-breakpoint"   )
add_test (name="rv64mi-p-csr"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64mi-p-csr"          )
add_test (name="rv64mi-p-illegal"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64mi-p-illegal"      )
add_test (name="rv64mi-p-ma_addr"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64mi-p-ma_addr"      )
add_test (name="rv64mi-p-ma_fetch"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64mi-p-ma_fetch"     )
add_test (name="rv64mi-p-mcsr"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64mi-p-mcsr"         )
#  add_test (name="rv64mi-p-sbreak"     group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'], ,         elf="riscv-tests/isa/rv64mi-p-sbreak"       )
add_test (name="rv64mi-p-scall"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64mi-p-scall"        )
add_test (name="rv64si-p-csr"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64si-p-csr"          )
add_test (name="rv64si-p-dirty"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64si-p-dirty"        )
add_test (name="rv64si-p-icache-alias", group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64si-p-icache-alias" )
add_test (name="rv64si-p-ma_fetch"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64si-p-ma_fetch"     )
#   add_test (name="rv64si-p-sbreak"    group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],  ,         elf="riscv-tests/isa/rv64si-p-sbreak"       )
add_test (name="rv64si-p-scall"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64si-p-scall"        )
add_test (name="rv64si-p-wfi"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64si-p-wfi"          )
add_test (name="rv64ua-p-amoadd_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoadd_d"     , skip=True )
add_test (name="rv64ua-p-amoadd_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoadd_w"     , skip=True )
add_test (name="rv64ua-p-amoand_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoand_d"     , skip=True )
add_test (name="rv64ua-p-amoand_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoand_w"     , skip=True )
add_test (name="rv64ua-p-amomax_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amomax_d"     , skip=True )
add_test (name="rv64ua-p-amomax_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amomax_w"     , skip=True )
add_test (name="rv64ua-p-amomaxu_d"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amomaxu_d"    , skip=True )
add_test (name="rv64ua-p-amomaxu_w"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amomaxu_w"    , skip=True )
add_test (name="rv64ua-p-amomin_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amomin_d"     , skip=True )
add_test (name="rv64ua-p-amomin_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amomin_w"     , skip=True )
add_test (name="rv64ua-p-amominu_d"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amominu_d"    , skip=True )
add_test (name="rv64ua-p-amominu_w"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amominu_w"    , skip=True )
add_test (name="rv64ua-p-amoor_d"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoor_d"      , skip=True )
add_test (name="rv64ua-p-amoor_w"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoor_w"      , skip=True )
add_test (name="rv64ua-p-amoswap_d"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoswap_d"    , skip=True )
add_test (name="rv64ua-p-amoswap_w"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoswap_w"    , skip=True )
add_test (name="rv64ua-p-amoxor_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoxor_d"     , skip=True )
add_test (name="rv64ua-p-amoxor_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-amoxor_w"     , skip=True )
add_test (name="rv64ua-p-lrsc"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-p-lrsc"         , skip=True )
add_test (name="rv64uc-p-rvc"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uc-p-rvc"          )
add_test (name="rv64ud-p-fadd"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-fadd"         )
add_test (name="rv64ud-p-fclass"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-fclass"       )
add_test (name="rv64ud-p-fcmp"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-fcmp"         )
add_test (name="rv64ud-p-fcvt"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-fcvt"         )
add_test (name="rv64ud-p-fcvt_w"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-fcvt_w"       )
add_test (name="rv64ud-p-fdiv"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-fdiv"         )
add_test (name="rv64ud-p-fmadd"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-fmadd"        )
add_test (name="rv64ud-p-fmin"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-fmin"         )
add_test (name="rv64ud-p-ldst"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-ldst"         )
add_test (name="rv64ud-p-move"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-move"         )
add_test (name="rv64ud-p-recoding"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-recoding"     )
add_test (name="rv64ud-p-structural"  , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-p-structural"   )
add_test (name="rv64um-p-div"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-div"          )
add_test (name="rv64um-p-divu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-divu"         )
add_test (name="rv64um-p-divuw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-divuw"        )
add_test (name="rv64um-p-divw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-divw"         )
add_test (name="rv64um-p-mul"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-mul"          )
add_test (name="rv64um-p-mulh"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-mulh"         )
add_test (name="rv64um-p-mulhsu"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-mulhsu"       )
add_test (name="rv64um-p-mulhu"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-mulhu"        )
add_test (name="rv64um-p-mulw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-mulw"         )
add_test (name="rv64um-p-rem"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-rem"          )
add_test (name="rv64um-p-remu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-remu"         )
add_test (name="rv64um-p-remuw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-remuw"        )
add_test (name="rv64um-p-remw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-p-remw"         )
                                        group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],
add_test (name="rv64ua-v-amoadd_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoadd_d"     , skip=True )
add_test (name="rv64ua-v-amoadd_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoadd_w"     , skip=True )
add_test (name="rv64ua-v-amoand_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoand_d"     , skip=True )
add_test (name="rv64ua-v-amoand_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoand_w"     , skip=True )
add_test (name="rv64ua-v-amomax_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amomax_d"     , skip=True )
add_test (name="rv64ua-v-amomax_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amomax_w"     , skip=True )
add_test (name="rv64ua-v-amomaxu_d"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amomaxu_d"    , skip=True )
add_test (name="rv64ua-v-amomaxu_w"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amomaxu_w"    , skip=True )
add_test (name="rv64ua-v-amomin_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amomin_d"     , skip=True )
add_test (name="rv64ua-v-amomin_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amomin_w"     , skip=True )
add_test (name="rv64ua-v-amominu_d"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amominu_d"    , skip=True )
add_test (name="rv64ua-v-amominu_w"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amominu_w"    , skip=True )
add_test (name="rv64ua-v-amoor_d"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoor_d"      , skip=True )
add_test (name="rv64ua-v-amoor_w"     , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoor_w"      , skip=True )
add_test (name="rv64ua-v-amoswap_d"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoswap_d"    , skip=True )
add_test (name="rv64ua-v-amoswap_w"   , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoswap_w"    , skip=True )
add_test (name="rv64ua-v-amoxor_d"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoxor_d"     , skip=True )
add_test (name="rv64ua-v-amoxor_w"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-amoxor_w"     , skip=True )
add_test (name="rv64ua-v-lrsc"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ua-v-lrsc"         , skip=True )
add_test (name="rv64uc-v-rvc"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uc-v-rvc"          )
add_test (name="rv64ud-v-fadd"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-fadd"         )
add_test (name="rv64ud-v-fclass"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-fclass"       )
add_test (name="rv64ud-v-fcmp"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-fcmp"         )
add_test (name="rv64ud-v-fcvt"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-fcvt"         )
add_test (name="rv64ud-v-fcvt_w"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-fcvt_w"       )
add_test (name="rv64ud-v-fdiv"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-fdiv"         )
add_test (name="rv64ud-v-fmadd"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-fmadd"        )
add_test (name="rv64ud-v-fmin"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-fmin"         )
add_test (name="rv64ud-v-ldst"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-ldst"         )
add_test (name="rv64ud-v-move"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-move"         )
add_test (name="rv64ud-v-recoding"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-recoding"     )
add_test (name="rv64ud-v-structural"  , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64ud-v-structural"   )
add_test (name="rv64uf-p-fadd"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-fadd"         )
add_test (name="rv64uf-p-fclass"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-fclass"       )
add_test (name="rv64uf-p-fcmp"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-fcmp"         )
add_test (name="rv64uf-p-fcvt"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-fcvt"         )
add_test (name="rv64uf-p-fcvt_w"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-fcvt_w"       )
add_test (name="rv64uf-p-fdiv"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-fdiv"         )
add_test (name="rv64uf-p-fmadd"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-fmadd"        )
add_test (name="rv64uf-p-fmin"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-fmin"         )
add_test (name="rv64uf-p-ldst"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-ldst"         )
add_test (name="rv64uf-p-move"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-move"         )
add_test (name="rv64uf-p-recoding"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-p-recoding"     )
add_test (name="rv64uf-v-fadd"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-fadd"         )
add_test (name="rv64uf-v-fclass"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-fclass"       )
add_test (name="rv64uf-v-fcmp"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-fcmp"         )
add_test (name="rv64uf-v-fcvt"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-fcvt"         )
add_test (name="rv64uf-v-fcvt_w"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-fcvt_w"       )
add_test (name="rv64uf-v-fdiv"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-fdiv"         )
add_test (name="rv64uf-v-fmadd"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-fmadd"        )
add_test (name="rv64uf-v-fmin"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-fmin"         )
add_test (name="rv64uf-v-ldst"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-ldst"         )
add_test (name="rv64uf-v-move"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-move"         )
add_test (name="rv64uf-v-recoding"    , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64uf-v-recoding"     )
add_test (name="rv64um-v-div"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-div"          )
add_test (name="rv64um-v-divu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-divu"         )
add_test (name="rv64um-v-divuw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-divuw"        )
add_test (name="rv64um-v-divw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-divw"         )
add_test (name="rv64um-v-mul"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-mul"          )
add_test (name="rv64um-v-mulh"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-mulh"         )
add_test (name="rv64um-v-mulhsu"      , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-mulhsu"       )
add_test (name="rv64um-v-mulhu"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-mulhu"        )
add_test (name="rv64um-v-mulw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-mulw"         )
add_test (name="rv64um-v-rem"         , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-rem"          )
add_test (name="rv64um-v-remu"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-remu"         )
add_test (name="rv64um-v-remuw"       , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-remuw"        )
add_test (name="rv64um-v-remw"        , group=['rv64', 'rv64imc', 'rv64imfc', 'rv64imfdc'],        elf="riscv-tests/isa/rv64um-v-remw"         }
