FROM msyksphinz/msrh:run_env

RUN apt install -y ruby
RUN apt install -y clang ccache

WORKDIR /work

COPY ./ /work/

WORKDIR /work/verilator_sim

RUN ["ls -1 /work/verilator_sim/"]
RUN ["/work/scripts/runtest.py", "--isa", "rv64imac", "-c", "tiny", "-t", "dhrystone"]
