    .section    .text
_start:
    addi	x1,  x0,  1
    addi	x2,  x1,  2
    addi	x3,  x2,  3
    addi	x4,  x3,  4
    addi	x5,  x4,  5
    addi	x6,  x5,  6
    addi	x7,  x6,  7
    addi	x8,  x7,  8
    addi	x9,  x8,  9
    addi	x10, x9, 10
    addi	x11, x10, 11
    addi	x12, x11, 12
    addi	x13, x12, 13
    addi	x14, x13, 14
    addi	x15, x14, 15
    addi	x16, x15, 16
    addi	x17, x16, 17
    addi	x18, x17, 18
    addi	x19, x18, 19
    addi	x20, x19, 20
    addi	x21, x20, 21
    addi	x22, x21, 22
    addi	x23, x22, 23
    addi	x24, x23, 24
    addi	x25, x24, 25
    addi	x26, x25, 26
    addi	x27, x26, 27
    addi	x28, x27, 28
    addi	x29, x28, 29
    addi	x30, x29, 30
    addi	x31, x30, 31
    addi	x1,  x31, 101
    addi	x2,  x1,  102
    addi	x3,  x2,  103
    addi	x4,  x3,  104
    addi	x5,  x4,  105
    addi	x6,  x5,  106
    addi	x7,  x6,  107
    addi	x8,  x7,  108
    addi	x9,  x8,  109
    addi	x10, x9,  110
    addi	x11, x10, 111
    addi	x12, x11, 112
    addi	x13, x12, 113
    addi	x14, x13, 114
    addi	x15, x14, 115
    addi	x16, x15, 116
    addi	x17, x16, 117
    addi	x18, x17, 118
    addi	x19, x18, 119
    addi	x20, x19, 120
    addi	x21, x20, 121
    addi	x22, x21, 122
    addi	x23, x22, 123
    addi	x24, x23, 124
    addi	x25, x24, 125
    addi	x26, x25, 126
    addi	x27, x26, 127
    addi	x28, x27, 128
    addi	x29, x28, 129
    addi	x30, x29, 130
    addi	x31, x30, 131

#include "common_pkg.S"

    TEST_FINISH
