# This is a basic workflow to help you get started with Actions

name: Build-RV64 configurations

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: ci_rv64_build
    strategy:
      matrix:
        system: ["ubuntu-20.04"]
        verilator: ["4.214"]

    # The type of runner that the job will run on
    runs-on: msyksphinz/msrh:run_env
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Apt updates
      - name: apt_updates
        run: |
          apt-get update && apt install -y tzdata
          apt install -y ruby git autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev libfl-dev device-tree-compiler ccache clang libelf-dev
        env:
            TZ: Asia/Tokyo
            DEBIAN_FRONTEND: noninteractive

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Tiny Build
        run: |
           docker-compose -f ./docker/top-test.yml build
           docker-compose -f ./docker/top-test.yml up --abort-on-container-exit
        working-directory: ./
