# This is a basic workflow to help you get started with Actions

name: Build-RV64 configurations

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: ci_rv64_build
    strategy:
      matrix:
        system: ["ubuntu-20.04"]
        verilator: ["4.214"]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.system }}
    container:
        image: verilator/verilator:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Apt updates
      - name: apt_updates
        run: |
          apt-get update && apt install -y tzdata
          apt install -y ruby git autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev libfl-dev device-tree-compiler ccache clang libelf-dev
        env:
            TZ: Asia/Tokyo
            DEBIAN_FRONTEND: noninteractive

      # # Build Verilator
      # - name: Cache Verilator ${{ matrix.verilator }}
      #   uses: actions/cache@v2.1.6
      #   id: cache-verilator
      #   with:
      #     path: verilator-${{ matrix.verilator }}
      #     key: ${{ matrix.system }}-verilator-${{ matrix.verilator }}
      #
      # - name: Compile Verilator ${{ matrix.verilator }}
      #   # if: steps.cache-verilator.outputs.cache-hit != 'true'
      #   run: |
      #     wget https://github.com/verilator/verilator/archive/refs/tags/v${{ matrix.verilator }}.tar.gz
      #     tar xvf v${{ matrix.verilator }}.tar.gz
      #     cd verilator-${{ matrix.verilator }}
      #     autoconf
      #     ./configure
      #     make
      # - name: Install Verilator ${{ matrix.verilator }}
      #   # if: steps.cache-verilator.outputs.cache-hit != 'true'
      #   run: |
      #     cd verilator-${{ matrix.verilator }}
      #     sudo make install
      #     verilator --version

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Build library
      - name: RV32IMC Tiny Build
        run: make -C verilator_sim/ rv32imc_tiny LINT=on DEBUG=off RV_FLEN=0
      - name: RV32IMFC Tiny Build
        run: make -C verilator_sim/ rv32imfc_tiny LINT=on DEBUG=off RV_FLEN=32
      - name: RV32IMFDC Tiny Build
        run: make -C verilator_sim/ rv32imfdc_tiny LINT=on DEBUG=off RV_FLEN=64

      ## - name: RV32 Small Build
      ##   run: make -C verilator_sim/ rv32_build CONF=small RV_XLEN=32 RV_FLEN=64 LINT=on VERILATOR_HOME=/usr/shared/verilator
      ##
      ## - name: RV32 Standard Build
      ##   run: make -C verilator_sim/ rv32imc_build CONF=standard RV_XLEN=32 RV_FLEN=64 LINT=on VERILATOR_HOME=/usr/shared/verilator
      ##
      ## - name: RV32 Big Build
      ##   run: make -C verilator_sim/ rv32_build CONF=big RV_XLEN=32 RV_FLEN=64 LINT=on VERILATOR_HOME=/usr/shared/verilator
      ##
      ## - name: RV32 Giant Build
      ##   run: make -C verilator_sim/ rv32_build CONF=giant RV_XLEN=32 RV_FLEN=64 LINT=on VERILATOR_HOME=/usr/shared/verilator
      ##
      - name: RV64IMC Tiny Build
        run: make -C verilator_sim/ rv64imc_tiny LINT=on DEBUG=off RV_FLEN=0
      - name: RV64IMFC Tiny Build
        run: make -C verilator_sim/ rv64imfc_tiny LINT=on DEBUG=off RV_FLEN=32
      - name: RV64IMFDC Tiny Build
        run: make -C verilator_sim/ rv64imfdc_tiny LINT=on DEBUG=off RV_FLEN=64

      ## - name: RV64 Small Build
      ##   run: make -C verilator_sim/ rv64_build CONF=small RV_XLEN=64 RV_FLEN=64 LINT=on VERILATOR_HOME=/usr/shared/verilator
      ##
      ## - name: RV64 Standard Build
      ##   run: make -C verilator_sim/ rv64_build CONF=standard RV_XLEN=64 RV_FLEN=64 LINT=on VERILATOR_HOME=/usr/shared/verilator
      ##
      ## - name: RV64 Big Build
      ##   run: make -C verilator_sim/ rv64_build CONF=big RV_XLEN=64 RV_FLEN=64 LINT=on VERILATOR_HOME=/usr/shared/verilator
      ##
      ## - name: RV64 Giant Build
      ##   run: make -C verilator_sim/ rv64_build CONF=giant RV_XLEN=64 RV_FLEN=64 LINT=on VERILATOR_HOME=/usr/shared/verilator
